### ISSUE TITLE
broken vendor/bin/npm if node is installed globally but without npm

### ISSUE THREAD

**Issue by nsams** [thecodingmachine/nodejs-installer#15]
This happened to me on archlinux where npm is an optional package. (I think also for debian)

Possible options:
- install node+npm locally
- fail with an error (telling the user that he has to install npm)
- generate only `vendor/bin/node` and no `/vendor/bin/npm`

The last option should be configurable as composer-extra-assets will always require npm.

**Comment by moufmouf** [comment]
Hey Niko,

I'm not completely sure, but I believe that up to npm 1.4, npm could be bundled without node. After npm 1.4, it seems to be bundled always with node (at least in binary distributions...)

Anyway, I applied a patch to nodejs-installer. I took the first option you suggest, i.e.: if Node is found but NPM is missing, I install both locally. Seems the best way to go since usually, you install Node using Nodejs-installer to get Bower or Gulp/Grunt, and all those require NPM.

I couldn't test it on my environment though. Could you let me know if it works on Arch?

**Comment by nsams** [comment]
works fine, thanks.
