### ISSUE TITLE
WINDOWS: altering path multiple times creating a too loong string

### ISSUE THREAD

**Issue by delmicio** [thecodingmachine/nodejs-installer#33]
Hi,
the npm.bat file appends PATH to PATH every time the bat is called, this should only be done the first time.

**Comment by moufmouf** [comment]
Hey @delmicio ,

When npm.bat calls "set PATH", the PATH is only modified for the current process, not the whole Windows environment. So unless npm is calling recursively itself (it seems a bit weird to me), this should not be an issue at all.

Are you facing a bug due to the length of the PATH environment variable? If yes, can you describe a way to reproduce the issue?

**Comment by delmicio** [comment]
Sorry, can not reproduce. :(
